networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.42.12.0/29
          gateway: 172.42.12.1

services:
  web:
    build: ./server
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: Oblaka
      MINIO_ROOT_PASSWORD: OblakaPass
      ADMIN_ACCESS_KEY: RTFM_abobaC70FLRMN0V
      MINIO_ALIAS: HeyHeyHey
      USER_ACCESS_KEY: oblakaKey
      USER_SECRET_KEY: b7IoXuR+Jk+pCceEhLpD4vQ3VXG3rmtRDcMF1EHL
      MAIN_BUCKET: mybucket
    mem_limit: 145mb
  client:
    ports:
      - "9001:9001"
      - "9000:9000"
    depends_on:
      - web
    network_mode: "host"
    build: ./client
    environment:
      USER_ACCESS_KEY: oblakaKey
      USER_SECRET_KEY: b7IoXuR+Jk+pCceEhLpD4vQ3VXG3rmtRDcMF1EHL
      MINIO_ALIAS: HeyHeyHey
      MAIN_BUCKET: mybucket